name: Deploy to Atatus

on:
  push:
    branches:
      - master

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use custom GitHub action from another repository
        uses: sharanraj124/test-deployment-marker-action-ts@v1.0.1
        with:
          api_url: "https://api.atatus.com/v2/projects"
          api_key: ${{ secrets.ATATUS_API_KEY }}
          changes: ${{ env.CHANGED_FILES }}
          revision: ${{ github.run_number }}
          release_stage: 'production'
          project_id: ${{ secrets.ATATUS_PROJECT_ID }}
