name: Deploy to Atatus

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: kubctl command
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'
        id: install

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build,, tag and push ecr registry
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: dev/nodeapp
          IMAGE_TAG: 1.0.0
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: update kube config file
        run: aws eks update-kubeconfig --name demo-cluster

      - name: deploy to eks
        run: |
          kubectl apply -f ./kubernetes/deployment.yml
          kubectl apply -f ./kubernetes/service.yml
          kubectl apply -f ./kubernetes/ingress.yml
# jobs:
#   example:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Use custom GitHub action from another repository
#         uses: sharanraj124/test-deployment-marker-action-ts@v1.0.1
#         with:
#           api_url: "https://api.atatus.com/v2/projects"
#           api_key: ${{ secrets.ATATUS_API_KEY }}
#           changes: ${{ env.CHANGED_FILES }}
#           revision: ${{ github.run_number }}
#           release_stage: 'production'
#           project_id: ${{ secrets.ATATUS_PROJECT_ID }}
